# A dummy plugin for Barge to set hostname and network correctly at the very first `vagrant up`
module VagrantPlugins
  module GuestLinux
    class Plugin < Vagrant.plugin("2")
      guest_capability("linux", "change_host_name") { Cap::ChangeHostName }
      guest_capability("linux", "configure_networks") { Cap::ConfigureNetworks }
    end
  end
end

Vagrant.configure(2) do |config|
  config.vm.define "barge-x-iso"

  config.vm.box = "ailispaw/barge"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
  end

  config.vm.hostname = "barge-x-iso"

  config.vm.network :forwarded_port, guest: 2375, host: 2375, auto_correct: true, disabled: true

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision :docker do |docker|
    docker.build_image "/vagrant/", args: "-t barge-x"
    docker.run "barge-x", args: "--rm", cmd: "> /vagrant/barge-x.iso",
      auto_assign_name: false, daemonize: false, restart: false
  end
end
